const { contextBridge, ipcRenderer } = require("electron");
const SOFTWARE_SEAL = "JXPB-PRE-5d9a0c3e17f48b26";
void SOFTWARE_SEAL;

contextBridge.exposeInMainWorld("desktop", {
  listBrowserAccounts: () => ipcRenderer.invoke('browser-accounts-list'),
  saveBrowserAccount: account => ipcRenderer.invoke('browser-account-save', account),
  importBrowserAccounts: accounts => ipcRenderer.invoke('browser-accounts-import', accounts),
  removeBrowserAccount: id => ipcRenderer.invoke('browser-account-remove', id),
  browserAccountCredential: id => ipcRenderer.invoke('browser-account-credential', id),
  updateBrowserAccountQuota: (id, status) => ipcRenderer.invoke('browser-account-quota', id, status),
  openBrowserWindow: () => ipcRenderer.invoke('browser-window-open'),
  minimizeBrowserWindow: () => ipcRenderer.invoke('browser-window-minimize'),
  closeBrowserWindow: () => ipcRenderer.invoke('browser-window-close'),
  setBrowserWindowTitle: title => ipcRenderer.invoke('browser-window-set-title', title),
  warmupBrowserWorkers: input => ipcRenderer.invoke('browser-workers-warmup', input),
  focusBrowserAccount: accountId => ipcRenderer.invoke('browser-focus-account', accountId),
  browserWorkersStatus: () => ipcRenderer.invoke('browser-workers-status'),
  readClipboardText: () => ipcRenderer.invoke('clipboard-read-text'),
  dispatchBrowserTask: task => ipcRenderer.invoke('browser-task-dispatch', task),
  reportBrowserTaskStatus: payload => ipcRenderer.invoke('browser-task-status', payload),
  takeBrowserCanvasTask: () => ipcRenderer.invoke('browser-task-take'),
  onBrowserCanvasTask: callback => ipcRenderer.on('browser-canvas-task', (_event, payload) => callback(payload)),
  onBrowserReadyBackfill: callback => ipcRenderer.on('browser-ready-backfill', (_event, payload) => callback(payload)),
  syncBrowserComposer: payload => ipcRenderer.invoke('browser-sync-composer', payload),
  onBrowserSyncComposer: callback => ipcRenderer.on('browser-sync-composer', (_event, payload) => callback(payload)),
  onBrowserPromptAddAccount: callback => ipcRenderer.on('browser-prompt-add-account', () => callback()),
  trustedClick: payload => ipcRenderer.invoke('browser-trusted-click', payload),
  trustedKey: payload => ipcRenderer.invoke('browser-trusted-key', payload),
  waitComposerReady: payload => ipcRenderer.invoke('browser-wait-composer', payload),
  ensureVideoMode: payload => ipcRenderer.invoke('browser-ensure-video-mode', payload),
  fillComposerPrompt: payload => ipcRenderer.invoke('browser-fill-prompt', payload),
  clickDolaSend: payload => ipcRenderer.invoke('browser-click-dola-send', payload),
  downloadBrowserVideo: payload => ipcRenderer.invoke('browser-video-download', payload),
  commitCanvasBackfill: payload => ipcRenderer.invoke('browser-commit-backfill', payload),
  browserOriginTask: () => ipcRenderer.invoke('browser-origin-task'),
  listBrowserBackfillCandidates: accountId => ipcRenderer.invoke('browser-backfill-candidates', accountId),
  peekCleanVideoUrl: payload => ipcRenderer.invoke('browser-clean-video', payload),
  uploadBrowserReferences: payload => ipcRenderer.invoke('browser-reference-upload', payload),
  chooseDoubao: () => ipcRenderer.invoke("choose-doubao"),
  doubaoPath: () => ipcRenderer.invoke("doubao-path"),
  listProfiles: () => ipcRenderer.invoke("list-profiles"),
  syncAccounts: () => ipcRenderer.invoke("sync-accounts"),
  addProfile: name => ipcRenderer.invoke("add-profile", name),
  renameProfile: (id, name) => ipcRenderer.invoke("rename-profile", id, name),
  removeProfile: id => ipcRenderer.invoke("remove-profile", id),
  openProfile: id => ipcRenderer.invoke("open-profile", id),
  sendToDoubao: job => ipcRenderer.invoke("send-to-doubao", job),
  stopDoubaoJob: jobId => ipcRenderer.invoke("stop-doubao-job", jobId),
  syncDoubaoResult: job => ipcRenderer.invoke("sync-doubao-result", job),
  taskSnapshots: ids => ipcRenderer.invoke("task-snapshots", ids),
  openTaskFolder: () => ipcRenderer.invoke("open-task-folder"),
  openJobFolder: jobId => ipcRenderer.invoke("open-job-folder", jobId),
  noWatermarkStatus: () => ipcRenderer.invoke("no-watermark-status"),
  setNoWatermarkEnabled: enabled => ipcRenderer.invoke("set-no-watermark-enabled", Boolean(enabled)),
  openNoWatermarkFolder: () => ipcRenderer.invoke("open-no-watermark-folder"),
  deleteHistoryJob: job => ipcRenderer.invoke("delete-history-job", job),
  openXianyuShop: () => ipcRenderer.invoke("open-xianyu-shop"),
  dataLocation: () => ipcRenderer.invoke("data-location"),
  resetUserData: () => ipcRenderer.invoke("reset-user-data"),
  licenseStatus: () => ipcRenderer.invoke("license-status"),
  activateLicense: key => ipcRenderer.invoke("activate-license", key),
  checkUpdate: () => ipcRenderer.invoke("check-update"),
  applyUpdate: () => ipcRenderer.invoke("apply-update"),
  onUpdateProgress: callback => ipcRenderer.on("update-progress", (_event, payload) => callback(payload)),
  ensureCanvasVideoPreview: src => ipcRenderer.invoke("ensure-canvas-video-preview", src),
  onDoubaoProgress: callback => ipcRenderer.on("doubao-progress", (_event, payload) => callback(payload)),
  onDoubaoJobState: callback => ipcRenderer.on("doubao-job-state", (_event, payload) => callback(payload)),
  onDoubaoResult: callback => ipcRenderer.on("doubao-result", (_event, payload) => callback(payload)),
  onDoubaoJobFailed: callback => ipcRenderer.on("doubao-job-failed", (_event, payload) => callback(payload)),
  onNoWatermarkStatus: callback => ipcRenderer.on("no-watermark-status-updated", (_event, payload) => callback(payload)),
  onLicenseStatus: callback => ipcRenderer.on("license-status-updated", (_event, payload) => callback(payload)),
  onProfilesUpdated: callback => ipcRenderer.on("profiles-updated", (_event, payload) => callback(payload))
});
